# -*- coding: utf-8 -*-
"""Практическое_задание_2_Чекмарева.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9mD7XIwnuFcpkME8HEZEqFUszprW7bP
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile decorators.py
# """
# Модуль с декораторами
# """
# import time
# from functools import wraps
# 
# # Декоратор для измерения времени выполнения функции
# def timer(func):
#     @wraps(func)
#     def wrapper(*args, **kwargs):
#         start = time.time()
#         result = func(*args, **kwargs)
#         end = time.time()
#         print(f"Функция {func.__name__} выполнена за {end - start:.4f} секунд")
#         return result
#     return wrapper
# 
# # Декоратор для логирования вызова функции
# def logger(func):
#     @wraps(func)
#     def wrapper(*args, **kwargs):
#         print(f"Вызов функции: {func.__name__} с аргументами: args={args}, kwargs={kwargs}")
#         return func(*args, **kwargs)
#     return wrapper
# 
# # Декоратор для проверки, что все аргументы — числа
# def validate_numbers(func):
#     @wraps(func)
#     def wrapper(*args, **kwargs):
#         for arg in args:
#             if not isinstance(arg, (int, float)):
#                 raise TypeError(f"Все аргументы должны быть числами! Получен: {type(arg)}")
#         return func(*args, **kwargs)
#     return wrapper

"""Эта ячейка создаёт файл decorators.py, содержащий три полезных декоратора:
@timer — измеряет время выполнения функции,
@logger — выводит информацию о вызове функции,
@validate_numbers — проверяет, что все аргументы — числа.
Эти декораторы можно применять к любым функциям для добавления полезного поведения без изменения их кода.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calculations.py
# """
# Модуль с математическими функциями
# """
# 
# import math
# 
# def linear(x):
#     """f(x) = 2x + 1"""
#     return 2 * x + 1
# 
# def quadratic(x):
#     """f(x) = x^2"""
#     return x ** 2
# 
# def sine(x):
#     """f(x) = sin(x)"""
#     return math.sin(x)
# 
# def exponential(x):
#     """f(x) = e^x"""
#     return math.exp(x)
# 
# def logarithm(x):
#     """f(x) = ln(x) (только x > 0)"""
#     if x <= 0:
#         raise ValueError("Аргумент логарифма должен быть > 0")
#     return math.log(x)

"""Эта ячейка создаёт файл calculations.py с пятью математическими функциями:
линейная, квадратичная, синус, экспонента и натуральный логарифм.
Они будут использоваться для вычисления значений на заданном отрезке.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile visualization.py
# """
# Модуль визуализации: график и таблица
# """
# import matplotlib.pyplot as plt
# 
# def plot_function(x_vals, y_vals, a, b, func_name):
#     """Строит график функции на отрезке [a, b]"""
#     plt.figure(figsize=(10, 5))
#     plt.plot(x_vals, y_vals, marker='o', linestyle='-', color='blue')
#     plt.title(f"График функции {func_name} на [{a}, {b}]")
#     plt.xlabel("x")
#     plt.ylabel("f(x)")
#     plt.grid(True)
#     plt.axhline(0, color='black', linewidth=0.5)
#     plt.axvline(0, color='black', linewidth=0.5)
#     plt.show()
# 
# def print_table(x_vals, y_vals):
#     """Выводит таблицу X и Y в две строки с выравниванием"""
#     print("X: ", end="")
#     for x in x_vals:
#         print(f"{x:8.3f}", end=" ")
#     print("\nY: ", end="")
#     for y in y_vals:
#         if y is None:
#             print(f"{'nan':>8}", end=" ")
#         else:
#             print(f"{y:8.3f}", end=" ")
#     print()  # новая строка в конце

"""Эта ячейка создаёт файл visualization.py с двумя функциями визуализации:

plot_function() — строит график зависимости Y от X с помощью библиотеки matplotlib,
print_table() — выводит значения X и Y в виде красиво отформатированной таблицы в две строки.

"""

from decorators import timer, logger, validate_numbers
from calculations import linear, quadratic, sine, exponential, logarithm
from visualization import plot_function, print_table
import math

# Словарь доступных функций
functions = {
    "1": ("linear", linear),
    "2": ("quadratic", quadratic),
    "3": ("sine", sine),
    "4": ("exponential", exponential),
    "5": ("logarithm", logarithm),
}

print("Добро пожаловать в программу построения графиков!")
print("Доступные функции:")
print("1. linear(x)     = 2x + 1")
print("2. quadratic(x)  = x^2")
print("3. sine(x)       = sin(x)")
print("4. exponential(x)= e^x")
print("5. logarithm(x)  = ln(x) (x > 0)")

# Выбор функции
choice = input("\nВыберите номер функции (1-5): ").strip()
if choice not in functions:
    print("Ошибка: неверный выбор!")
else:
    func_name, func = functions[choice]

    try:
        # Ввод диапазона и шага
        a = float(input("Введите начало отрезка (a): "))
        b = float(input("Введите конец отрезка (b): "))
        step = float(input("Введите шаг: "))

        if step <= 0:
            print("Шаг должен быть положительным!")
        elif a >= b:
            print("Начало отрезка должно быть меньше конца!")
        else:
            # Генерируем вектор X
            x_vals = []
            x = a
            while x <= b:
                x_vals.append(x)
                x += step
                # Округляем, чтобы избежать ошибок с плавающей точкой
                x = round(x, 10)

            # Вычисляем Y с обработкой ошибок (например, для log(x))
            y_vals = []
            for x in x_vals:
                try:
                    y = func(x)
                    y_vals.append(y)
                except (ValueError, OverflowError):
                    y_vals.append(None)  # Помечаем как недопустимое

            # Выводим таблицу
            print("\nТаблица значений:")
            print_table(x_vals, y_vals)

            # Удаляем точки, где y = None (например, log(-1))
            x_clean = []
            y_clean = []
            for x, y in zip(x_vals, y_vals):
                if y is not None and abs(y) < 1e10:  # избегаем огромных значений
                    x_clean.append(x)
                    y_clean.append(y)

            if x_clean:
                # Строим график
                plot_function(x_clean, y_clean, a, b, func_name)
            else:
                print("Нет допустимых точек для построения графика.")

    except ValueError:
        print("Ошибка: введите корректные числа!")

"""Эта ячейка — главная часть программы. Она:

Подключает все созданные модули, выводит список доступных функций, запрашивает у пользователя диапазон [a, b] и шаг, вычисляет значения X и Y, печатает таблицу значений, строит график выбранной функции.
Программа также обрабатывает ошибки (например, логарифм от отрицательного числа) и корректно работает с некорректным вводом.
"""